### ISSUE TITLE
Add heading styles

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/wireframe#3]
should go into _base.scss and use redacted font.

**Comment by ryuhhnn** [comment]
Would it be necessary to even create heading style? Since you included redacted in the html tag, there really isn't a need for it elsewhere unless you want to override the style. The build in header tags also serve an okay purpose as far as sizing goes, unless you wanted there to be different sizes?

**Comment by agauniyal** [comment]
Ah I must've forgotten about default sizes of H{1..6} tags. I'll be closing this, thanks @ryuhhnn.

**Comment by ryuhhnn** [comment]
No worries! Just figured leaving it out would make for cleaner code :)
