### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by wescley** [agauniyal/wireframe#32]
Hi,

Good Evening,

I try to install the project, bur i have the following problem:

npm notice created a lockfile as package-lock.json. You should commit this file.
added 659 packages from 518 contributors and audited 3449 packages in 158.538s
found 12 vulnerabilities (2 low, 2 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Thanks

**Comment by ryuhhnn** [comment]
Hey @wescley! I don't think this project has been maintained in quite a while, but that error you're seeing is just a warning that there are outdated dependencies. If you'd like to submit a PR to update them and include the package-lock.json file you're more than welcome! Otherwise I'm going to go ahead and close this issue since it's nothing that will prohibit installation, just a warning :)

**Comment by wescley** [comment]
Thanks @ryuhhnn 

I did the PR33

holds
